# -*- coding: utf-8 -*-
"""Copie de EMSE - Workshop 2020 - YOLO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZhuiuiinknvWw8WaKl2hEP_vunhKCUn

# Run YOLO V3 on Colab for images/videos

Hello there,
Today, we will be discussing how can we use the Darknet project on Google Colab platform. For those who are not familiar with these terms:

- The Darknet project is an open-source written in C, which is a framework to develop deep neural networks.
- Yolo V3 is an object detection algorithm. It is one of the state of the art solution when **accuracy/processing power needed** metric is considered.
- Google Cola is a cloud-based data science workspace similar to the jupyter notebook. Each Collabrotary session is equipped with a virtual machine running 13 GB of ram and either a CPU, GPU, or TPU processor. In most case, all the required packages are already installed on these machines and you can quite easily start development using Google Collaboratory. It saves us from installing process and it provides us **easy to accessible GPU's** which is also **free** under some constraints.

Have a look Ted Talk by Joseph Redmon the developer of the darknet project. The talk is about Darknet and YOLO projects which titled as “How computers learn to recognize objects instantly” . Darknet project aims to create a new neural network framework which is completely focused on simplicity and performance. The thing which I like about is its clarity and performance. All the code is written in C, to define a deep learning network you should only create a config file which defines the layers. By this way, it does not lose its performance capabilities also it provides us easy to use interface for development with this library.

Since I love both YOLO project and Google Colab, I decided to create a tutorial to use them together. I create a GitHub repository and a Collaboratory notebook for this purpose

- [Colab Notebook](https://colab.research.google.com/drive/1DcXQ_pLtLVvQAwILZR-kF0ZJwhkp11Jl)
- [mozanunal/yoloOnGoogleColab](https://github.com/mozanunal/yoloOnGoogleColab)

{% youtube Cgxsv1riJhI%}

**Please check**
- [YOLO website](https://pjreddie.com/darknet/yolo/)
- [Darknet website](https://pjreddie.com/darknet/)
- [YOLOV3 Paper](https://arxiv.org/abs/1804.02767)

## Install
Go to the directory, clear and install everthing


*   Clone the project
*   Change make file configurations and make OPENCV and GPU enable
*   Install opencv library
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2, os
import matplotlib.pyplot as plt
# %matplotlib inline

# Commented out IPython magic to ensure Python compatibility.
!ls
!cd /content
!rm -fr darknet
!git clone https://github.com/AlexeyAB/darknet/
# % cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/g' Makefile
!sed -i 's/GPU=0/GPU=1/g' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/g' Makefile
!apt update
!apt-get install libopencv-dev

"""## `Compile and Configure`


* Compile YOLO
* Download YOLO weights
"""

!make &> compile.log

!pip install gdown

!gdown https://drive.google.com/uc?id=1ZpR9zHQP4lT2rE3RXxVdGJY4ftj1_DJY

"""## Test An Image"""

def predictImage(imageDir):
  os.system("cd /content/darknet && ./darknet detect cfg/yolov3.cfg yolov3.weights {}".format(imageDir))#pour se mettre dans le bon endroit
  image = cv2.imread("/content/darknet/predictions.jpg")
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  #plt.rcParams['figure.figsize'] = [10, 5]
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

!wget https://github.com/mozanunal/yoloOnGoogleColab/raw/master/test/test.jpg

!ls

predictImage("test.jpg")

"""## Test with Video"""

def predictVideo(videoDir):
  os.system(""" cd /content/darknet && ./darknet detector demo cfg/coco.data cfg/yolov3.cfg yolov3.weights \
  -dont_show {} -i 0 -out_filename res.avi
  """.format(videoDir))

!wget https://github.com/mozanunal/yoloOnGoogleColab/raw/master/test/test.avi

!ls

predictVideo("test.avi")

!du -h res.avi







"""**Download** res.avi using Files tab and play it."""

